INSERT INTO medias (id, name) values(1, 'Classical');
INSERT INTO medias (id, name) values(2, 'Modern');
INSERT INTO medias (id, name) values(3, 'Jazz');
INSERT INTO medias (id, name) values(4, 'Country');
INSERT INTO medias (id, name) values(5, 'Bluegrass');
INSERT INTO medias (id, name) values(6, 'Rock');
INSERT INTO medias (id, name) values(7, 'Folk');
INSERT INTO medias (id, name) values(8, 'Rockabilly');
INSERT INTO medias (id, name) values(9, 'Metal');
INSERT INTO medias (id, name) values(10,'Jam');